baseURL = "https://saifulmqdr.ml"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Saiful Miqdar"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
ignoreErrors = ["error-remote-getjson"]
# Enable Disqus
disqusShortname = "disqus_1JXiWYQryV"

# Google Analytics
gtagId = "G-GS326RN87V"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Saiful Miqdar"
author = "Saiful Miqdar"
copyright = "2020-2021"
description = "I'am toxic but not stupid"
profilePicture = "images/profile.png"
keywords = ""
favicon = "favicons/profile.png"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
contactFormAction = "https://formspree.io/f/xknkngpn"
# Google Site Verify
googleSiteVerify = "iTECoUQSJq5XUI4vxzjEXcGhfca370eLbePxOoleXMg"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/mwlite/in/saiful-miqdar-7050511b1"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/bitch-code"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/saiful_mqdr"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:pennysxploit@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  weight = 400
  identifier = "contact"
  url = "/contact/"
  
